title: Aicrion Date Converter
description: >-
  High-performance PHP 8.2+ library for converting between Gregorian,
  Jalali (Persian/Shamsi), and Hijri (Islamic/Qamari) calendars.

plugins:
  - jekyll-relative-links

show_downloads: false

url: "https://aicrion.github.io"
baseurl: "/date-converter-php"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
